import { Component } from '@angular/core';
import { ReplaySubject, throwError, of, EMPTY, retry, catchError, timer, Observable } from 'rxjs';

import { ExerciseService } from '../exercise.service';

@Component({
  selector: 'rxw-error-handling',
  templateUrl: './error-handling.component.html',
})
export class ErrorHandlingComponent {

  logStream$ = new ReplaySubject<unknown>();

  constructor(private es: ExerciseService) { }

  /**
   * Das Observable aus `this.es.randomError()` liefert mit hoher Wahrscheinlichkeit einen Fehler.
   * Probiere verschiedene Strategien aus, um den Fehler zu behandeln:
   * - wiederholen
   * - Fehler weiterwerfen
   * - Fehler umwandeln (in ein normales Element)
   * - Fehler verschlucken/ignorieren
   */

  start() {
    this.es.randomError().pipe(
      catchError(err => {
        // Fehler ersetzen
        // return of('Fehler ersetzt!', '!!!');

        // Fehler verschlucken
        // return new Observable();
        // return of();
        // return EMPTY;

        // Fehler weiterwerfen
        // return new Observable(sub => sub.error('Mein Fehler!'));
        // return throwError(() => 'Mein Fehler!');
        throw 'FEHLER!!!';
        // throw err;
      })
    ).subscribe({
      next: e => this.logStream$.next(e),
      error: err => this.logStream$.next('‚ùå ERROR: ' + err)
    });
  }
}
